In [1]:
import pandas as pd
import numpy as np
import os
lc0711 = pd.read_csv('LoanStats3a.csv', engine='python')

## Select columns composed with more than 80% of NaN

#### 1. Create Series of bool values

In [3]:
lc0711.isnull().head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,True,True,False,False,False,False,False,False,False,False,...,True,True,False,False,True,True,True,True,True,True
1,True,True,False,False,False,False,False,False,False,False,...,True,True,False,False,True,True,True,True,True,True
2,True,True,False,False,False,False,False,False,False,False,...,True,True,False,False,True,True,True,True,True,True
3,True,True,False,False,False,False,False,False,False,False,...,True,True,False,False,True,True,True,True,True,True
4,True,True,False,False,False,False,False,False,False,False,...,True,True,False,False,True,True,True,True,True,True

In [5]:
lc0711.isnull().sum().head()

id                 42539
member_id          42542
loan_amnt              7
funded_amnt            7
funded_amnt_inv        7
dtype: int64

In [8]:
lc0711.isnull().sum()/len(lc0711) # (Series) +-/x (some value) = (Series)

id                                            0.999929
member_id                                     1.000000
loan_amnt                                     0.000165
funded_amnt                                   0.000165
funded_amnt_inv                               0.000165
term                                          0.000165
int_rate                                      0.000165
installment                                   0.000165
grade                                         0.000165
sub_grade                                     0.000165
emp_title                                     0.061845
emp_length                                    0.000165
home_ownership                                0.000165
annual_inc                                    0.000259
verification_status                           0.000165
issue_d                                       0.000165
loan_status                                   0.000165
pymnt_plan                                    0.000165
url                                           1.000000
desc                                          0.312609
purpose                                       0.000165
title                                         0.000447
zip_code                                      0.000165
addr_state                                    0.000165
dti                                           0.000165
delinq_2yrs                                   0.000846
earliest_cr_line                              0.000846
inq_last_6mths                                0.000846
mths_since_last_delinq                        0.633116
mths_since_last_record                        0.914155
                                                ...
sec_app_open_acc                              1.000000
sec_app_revol_util                            1.000000
sec_app_open_act_il                           1.000000
sec_app_num_rev_accts                         1.000000
sec_app_chargeoff_within_12_mths              1.000000
sec_app_collections_12_mths_ex_med            1.000000
sec_app_mths_since_last_major_derog           0.999976
hardship_flag                                 0.000188
hardship_type                                 1.000000
hardship_reason                               1.000000
hardship_status                               1.000000
deferral_term                                 1.000000
hardship_amount                               1.000000
hardship_start_date                           1.000000
hardship_end_date                             1.000000
payment_plan_start_date                       1.000000
hardship_length                               1.000000
hardship_dpd                                  1.000000
hardship_loan_status                          1.000000
orig_projected_additional_accrued_interest    1.000000
hardship_payoff_balance_amount                1.000000
hardship_last_payment_amount                  0.999976
disbursement_method                           0.000165
debt_settlement_flag                          0.000188
debt_settlement_flag_date                     0.996333
settlement_status                             0.996333
settlement_date                               0.996333
settlement_amount                             0.996333
settlement_percentage                         0.996333
settlement_term                               0.996333
Length: 145, dtype: float64

In [9]:
lc0711.isnull().sum()/len(lc0711)>=0.8 # (Series) (logical operation) = (bool Series)

id                                             True
member_id                                      True
loan_amnt                                     False
funded_amnt                                   False
funded_amnt_inv                               False
term                                          False
int_rate                                      False
installment                                   False
grade                                         False
sub_grade                                     False
emp_title                                     False
emp_length                                    False
home_ownership                                False
annual_inc                                    False
verification_status                           False
issue_d                                       False
loan_status                                   False
pymnt_plan                                    False
url                                            True
desc                                          False
purpose                                       False
title                                         False
zip_code                                      False
addr_state                                    False
dti                                           False
delinq_2yrs                                   False
earliest_cr_line                              False
inq_last_6mths                                False
mths_since_last_delinq                        False
mths_since_last_record                         True
                                              ...
sec_app_open_acc                               True
sec_app_revol_util                             True
sec_app_open_act_il                            True
sec_app_num_rev_accts                          True
sec_app_chargeoff_within_12_mths               True
sec_app_collections_12_mths_ex_med             True
sec_app_mths_since_last_major_derog            True
hardship_flag                                 False
hardship_type                                  True
hardship_reason                                True
hardship_status                                True
deferral_term                                  True
hardship_amount                                True
hardship_start_date                            True
hardship_end_date                              True
payment_plan_start_date                        True
hardship_length                                True
hardship_dpd                                   True
hardship_loan_status                           True
orig_projected_additional_accrued_interest     True
hardship_payoff_balance_amount                 True
hardship_last_payment_amount                   True
disbursement_method                           False
debt_settlement_flag                          False
debt_settlement_flag_date                      True
settlement_status                              True
settlement_date                                True
settlement_amount                              True
settlement_percentage                          True
settlement_term                                True
Length: 145, dtype: bool

#### 2. creating column index list using bool series

In [20]:
bool_series = lc0711.isnull().sum()/len(lc0711)>=0.8
bool_series

id                                             True
member_id                                      True
loan_amnt                                     False
funded_amnt                                   False
funded_amnt_inv                               False
term                                          False
int_rate                                      False
installment                                   False
grade                                         False
sub_grade                                     False
emp_title                                     False
emp_length                                    False
home_ownership                                False
annual_inc                                    False
verification_status                           False
issue_d                                       False
loan_status                                   False
pymnt_plan                                    False
url                                            True
desc                                          False
purpose                                       False
title                                         False
zip_code                                      False
addr_state                                    False
dti                                           False
delinq_2yrs                                   False
earliest_cr_line                              False
inq_last_6mths                                False
mths_since_last_delinq                        False
mths_since_last_record                         True
                                              ...
sec_app_open_acc                               True
sec_app_revol_util                             True
sec_app_open_act_il                            True
sec_app_num_rev_accts                          True
sec_app_chargeoff_within_12_mths               True
sec_app_collections_12_mths_ex_med             True
sec_app_mths_since_last_major_derog            True
hardship_flag                                 False
hardship_type                                  True
hardship_reason                                True
hardship_status                                True
deferral_term                                  True
hardship_amount                                True
hardship_start_date                            True
hardship_end_date                              True
payment_plan_start_date                        True
hardship_length                                True
hardship_dpd                                   True
hardship_loan_status                           True
orig_projected_additional_accrued_interest     True
hardship_payoff_balance_amount                 True
hardship_last_payment_amount                   True
disbursement_method                           False
debt_settlement_flag                          False
debt_settlement_flag_date                      True
settlement_status                              True
settlement_date                                True
settlement_amount                              True
settlement_percentage                          True
settlement_term                                True
Length: 145, dtype: bool

In [15]:
NaN_columns = lc0711.columns[bool_series]
NaN_columns

Index(['id', 'member_id', 'url', 'mths_since_last_record', 'next_pymnt_d',
       'mths_since_last_major_derog', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'tot_coll_amt', 'tot_cur_bal',
       'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m',
       'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m',
       'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal',
       'bc_open_to_buy', 'bc_util', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq',
       'mths_since_recent_inq', 'mths_since_recent_revol_delinq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit',
       'revol_bal_joint', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths',
       'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util',
       'sec_app_open_act_il', 'sec_app_num_rev_accts',
       'sec_app_chargeoff_within_12_mths',
       'sec_app_collections_12_mths_ex_med',
       'sec_app_mths_since_last_major_derog', 'hardship_type',
       'hardship_reason', 'hardship_status', 'deferral_term',
       'hardship_amount', 'hardship_start_date', 'hardship_end_date',
       'payment_plan_start_date', 'hardship_length', 'hardship_dpd',
       'hardship_loan_status', 'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object')

In [18]:
lc0711[NaN_columns].head()

,id,member_id,url,mths_since_last_record,next_pymnt_d,mths_since_last_major_derog,annual_inc_joint,dti_joint,verification_status_joint,tot_coll_amt,...,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
lc0711.ix[:, bool_series].head() # Same result

,id,member_id,url,mths_since_last_record,next_pymnt_d,mths_since_last_major_derog,annual_inc_joint,dti_joint,verification_status_joint,tot_coll_amt,...,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN